base_local_planner: dwa_local_planner/DWAPlannerROS
DWAPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.0
  min_rot_vel: 0.2
  max_rot_vel: 0.5
  min_in_place_rotational_vel: 0.3

  acc_lim_th: 1.0
  acc_lim_x: 1.0

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  holonomic_robot: false
  
  global_frame_id: aero/odom